"""Initial Migration

Revision ID: 9813ddb11b6d
Revises: ac5a3bffeb09
Create Date: 2021-11-15 13:46:35.904477

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9813ddb11b6d'
down_revision = 'ac5a3bffeb09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('uploads', 'upload')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('uploads', sa.Column('upload', sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
